# Generated by Django 5.2 on 2025-05-16 01:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("refrigerator", "0002_alter_item_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="date_of_purchase",
            new_name="added_on",
        ),
    ]
